# fly.toml app configuration file generated for ffbot on 2026-06-08T03:39:06Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ffbot'
primary_region = 'ams'

[build]

[env]
  TZ = 'Asia/Kuala_Lumpur'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
